#! /bin/bash

CONFIG=${0%/*}/config
GATE_URL="https://llamalab.com/automate/cloud/message"

function usage() {
    echo "Usage $0:"
    echo "-p: concerns the permanent notification"
    echo "-h: shows this help"
    exit
}

PERMANENT="false"
VISIBLE="true"
TITLE=""

while getopts ":ph" o; do
    case "${o}" in
        p)
            PERMANENT="true"
            ;;
        * | h)
            usage
	    ;;
    esac
done
shift $((OPTIND-1))

[[ $# == 0 ]] && VISIBLE="false"

function initError() {
    echo "### AUTO GENERATED CONFIGURATION ###" >> $CONFIG
    echo -e "\nDESTINATION_MAIL=\"\"" >> $CONFIG
    echo "SECRET=\"\"" >> $CONFIG
    echo "Configuration file initiated"
    exit
}

! [[ -f $CONFIG ]] && initError

source $CONFIG

function notify() {

    BASE_CONTENT="{"
    BASE_CONTENT+='"secret": "'"$SECRET"'",'
    BASE_CONTENT+='"to": "'"$DESTINATION_MAIL"'",'
    BASE_CONTENT+='"device": null,'
    BASE_CONTENT+='"payload": "'
    BASE_CONTENT+='{'
    BASE_CONTENT+='\"permanent\":\"'$PERMANENT'\",'
    BASE_CONTENT+='\"visible\": \"'$VISIBLE'\",'
    BASE_CONTENT+='\"title\": \"'$1'\",'
    BASE_CONTENT+='\"content\": \"'$2'\"'
    BASE_CONTENT+='}"}'

    RULE='/<h1>.*<\/h1>/{s=index($0,">"); e=index($0, "</"); print substr($0, s + 1, e - s - 1) }'

    curl -X POST -H "Content-Type: application/json" -d "$BASE_CONTENT" $GATE_URL 2>&1 | awk "$RULE"
}

notify "$@"
